# Yarn 4 Configuration for node-modules mode with global cache
# Uses hardlinks to save disk space while maintaining compatibility

enableGlobalCache: true

# Node linker mode
# pnp: Plug'n'Play mode (not compatible with browser extensions)
# node-modules: Traditional mode (recommended for this project)
nodeLinker: node-modules
nmMode: hardlinks-global

# Compression and telemetry
compressionLevel: mixed
enableTelemetry: false
