/**
 * Design tokens — single source of truth for visual style.
 *
 * These values are consumed by:
 *  - src/ui/theme.ts          (MUI Theme used by popup/options React UI)
 *  - src/scss/_tokens.scss    (auto-generated by scripts/generate-scss-tokens.js,
 *                              consumed by SCSS files when needed)
 *
 * To change the visual style of the extension, edit this file.
 */

export const tokens = {
  color: {
    brand: {
      primary: '#2563eb',
      secondary: '#7c3aed'
    },
    status: {
      success: '#2e7d32',
      error: '#d32f2f',
      warning: '#ed6c02',
      info: '#0288d1'
    }
  },
  space: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32
  },
  radius: {
    sm: 4,
    md: 8,
    lg: 12
  }
} as const;

export type DesignTokens = typeof tokens;
